"""phase5: plugin_runs

Revision ID: 315b7e1f6707
Revises: 839d6ac056bc
Create Date: 2026-04-20 17:16:04.264116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from fastapi_users_db_sqlalchemy.generics import GUID


# revision identifiers, used by Alembic.
revision: str = '315b7e1f6707'
down_revision: Union[str, Sequence[str], None] = '839d6ac056bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plugin_runs',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('case_id', GUID(), nullable=False),
    sa.Column('input_entity_id', GUID(), nullable=True),
    sa.Column('plugin_name', sa.String(length=128), nullable=False),
    sa.Column('plugin_version', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False, server_default='running'),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('entities_created_count', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('relationships_created_count', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('evidence_count', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('created_by', GUID(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['input_entity_id'], ['entities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plugin_runs_case_id'), 'plugin_runs', ['case_id'], unique=False)
    op.create_index(op.f('ix_plugin_runs_input_entity_id'), 'plugin_runs', ['input_entity_id'], unique=False)
    op.create_index(op.f('ix_plugin_runs_plugin_name'), 'plugin_runs', ['plugin_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plugin_runs_plugin_name'), table_name='plugin_runs')
    op.drop_index(op.f('ix_plugin_runs_input_entity_id'), table_name='plugin_runs')
    op.drop_index(op.f('ix_plugin_runs_case_id'), table_name='plugin_runs')
    op.drop_table('plugin_runs')
    # ### end Alembic commands ###
