"""phase4: evidence

Revision ID: 839d6ac056bc
Revises: e638ce7e3b34
Create Date: 2026-04-18 19:17:11.457581

"""

from collections.abc import Sequence

import sqlalchemy as sa
from fastapi_users_db_sqlalchemy.generics import GUID

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "839d6ac056bc"
down_revision: str | Sequence[str] | None = "e638ce7e3b34"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "evidence",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("case_id", GUID(), nullable=False),
        sa.Column("entity_id", GUID(), nullable=True),
        sa.Column("source_plugin", sa.String(length=128), nullable=False),
        sa.Column("query", sa.String(length=1024), nullable=False),
        sa.Column("response_hash", sa.String(length=64), nullable=False),
        sa.Column("response_uri", sa.String(length=512), nullable=False),
        sa.Column("response_bytes", sa.BigInteger(), nullable=False),
        sa.Column("response_content_type", sa.String(length=128), nullable=True),
        sa.Column(
            "timestamp", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("reproducibility_spec", sa.JSON(), nullable=False),
        sa.Column("created_by", GUID(), nullable=True),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["entity_id"], ["entities.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_evidence_case_id"), "evidence", ["case_id"], unique=False)
    op.create_index(op.f("ix_evidence_entity_id"), "evidence", ["entity_id"], unique=False)
    op.create_index(op.f("ix_evidence_response_hash"), "evidence", ["response_hash"], unique=False)
    op.create_index(op.f("ix_evidence_source_plugin"), "evidence", ["source_plugin"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_evidence_source_plugin"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_response_hash"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_entity_id"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_case_id"), table_name="evidence")
    op.drop_table("evidence")
    # ### end Alembic commands ###
