"""phase3: relationships

Revision ID: e638ce7e3b34
Revises: 9702779a9df6
Create Date: 2026-04-18 17:34:38.621524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from fastapi_users_db_sqlalchemy.generics import GUID


# revision identifiers, used by Alembic.
revision: str = 'e638ce7e3b34'
down_revision: Union[str, Sequence[str], None] = '9702779a9df6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relationships',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('case_id', GUID(), nullable=False),
    sa.Column('src_entity_id', GUID(), nullable=False),
    sa.Column('dst_entity_id', GUID(), nullable=False),
    sa.Column('rel_type', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_plugin', sa.String(length=128), nullable=True),
    sa.Column('attrs', sa.JSON(), nullable=False),
    sa.Column('created_by', GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dst_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['src_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relationships_case_id'), 'relationships', ['case_id'], unique=False)
    op.create_index(op.f('ix_relationships_dst_entity_id'), 'relationships', ['dst_entity_id'], unique=False)
    op.create_index(op.f('ix_relationships_rel_type'), 'relationships', ['rel_type'], unique=False)
    op.create_index(op.f('ix_relationships_src_entity_id'), 'relationships', ['src_entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_relationships_src_entity_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_rel_type'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_dst_entity_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_case_id'), table_name='relationships')
    op.drop_table('relationships')
    # ### end Alembic commands ###
